name: Build Project

on: 
    push:
        branches:
            -  main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build Project

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.x'
                cache: true

            - name: Build Net
              run:  dotnet build ./src/Todo.Api.sln

            - name: Test Net
              run:  dotnet test ./src/Todo.Api.sln --no-build --logger trx --results-directory "TestResults"

            - uses: actions/upload-artifact@v4
              with:
                name: dotnet-test-results
                path: TestResults

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              working-directory: ./src/web
              run: 
                npm install
                npm run build       